export const ADD_TODO = "ADD_TODO";
export const DELETE_TODO = "DELETE_TODO";
export const EDIT_TODO = "EDIT_TODO";
export const COMPLETE_TODO = "COMPLETE_TODO";
export const COMPLETE_ALL_TODO = "COMPLETE_ALL_TODO";
export const CLEAR_COMPLETED = "CLEAR_COMPLETED";
export const SET_VISIBLE_FILTER = "SET_VISIBLE_FILTER";
